name: "Release a tag"
on: push

jobs:
  test-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test Unit
        run: go test -v ./...
