name: Test Integration
on: push

jobs:
  test-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Integration
        run: make test-integration
      - name: Coverage report
        uses: ncruces/go-coverage-report@f1283391eaeaf8137046f83ab02c890c4719f643
        with:
          badge-title: Coverage (integration)
          coverage-file: assets/coverage/integration/coverage.out
          report: true
          output-path: assets/coverage/integration
          chart: true
