name: Test Unit
on: push

jobs:
  test-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Unit
        run: make test-unit
      - name: Coverage report
        uses: ncruces/go-coverage-report@57ac6f0f19874f7afbab596105154f08004f482e
        with:
          badge-title: Coverage (unit)
          coverage-file: assets/coverage/unit/coverage.out
          report: true
          output-dir: assets/coverage/unit
          chart: true
