name: Test Integration
on: push

jobs:
  test-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Integration
        run: make test-integration
      - name: Coverage report
        uses: mgerasimchuk/go-coverage-report@custom-report-path
        with:
          badge-title: Coverage (integration)
          coverage-file: assets/coverage/integration/coverage.out
          report: true
          report-path: assets/coverage/integration
          chart: true
